# This file was generated by GoReleaser. DO NOT EDIT.
cask "percy" do
  version "0.409.936625127"

  on_macos do
    on_intel do
      sha256 "f2771ced8e88086e3a1f4e8fae723cc8139fc2e36471800cacca0b330ba856be"
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_darwin_amd64"
      binary "percy_darwin_amd64", target: "percy"
    end
    on_arm do
      sha256 "39773f6bacb7b8266695299c53d917768e02fe6cadbd619129dcff33fff40e56"
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_darwin_arm64"
      binary "percy_darwin_arm64", target: "percy"
    end
  end

  on_linux do
    on_intel do
      sha256 "331ac4b6d785e042112514098298d06e48fd3ecdd8be206f79148897c2096a55"
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_linux_amd64"
      binary "percy_linux_amd64", target: "percy"
    end
    on_arm do
      sha256 "81a4b638570b8c647929ca5090d01a166a4beea055d4b8bc62c13b48fbbc3f8e"
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_linux_arm64"
      binary "percy_linux_arm64", target: "percy"
    end
  end

  name "percy"
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/tgruben-circuit/percy"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required

end
