# This file was generated by GoReleaser. DO NOT EDIT.
cask "percy" do
  name "percy"
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/tgruben-circuit/percy"
  version "0.309.935423442"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_darwin_amd64"
      sha256 "985214e340e2c37f42d9357574b7c9c663dadb2a7eeb4578d50943dca72ab44c"
      binary "percy_darwin_amd64", target: "percy"
    end
    on_arm do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_darwin_arm64"
      sha256 "3843e827603190b5e72f8469c11311a6d3590b1e92112b62b55aed231e25a8c3"
      binary "percy_darwin_arm64", target: "percy"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_linux_amd64"
      sha256 "e558c42be5b52e6a87050386b0f5a4bf93a7befbc1d2643767c42f20be5c8382"
      binary "percy_linux_amd64", target: "percy"
    end
    on_arm do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_linux_arm64"
      sha256 "107c020970b3f8d71f194a6c2fc3e36f623a520b423e07b870fc38ddb356894c"
      binary "percy_linux_arm64", target: "percy"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required
end
