# This file was generated by GoReleaser. DO NOT EDIT.
cask "percy" do
  name "percy"
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/tgruben-circuit/percy"
  version "0.251.953415700"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_darwin_amd64"
      sha256 "1bdf733285c5c737f2b3c18cc97183ea1b3fa2fb9676771db059b4ca2a216f2c"
      binary "percy_darwin_amd64", target: "percy"
    end
    on_arm do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_darwin_arm64"
      sha256 "f389aeb44fd8e55ab351aff01c5eed11fe47116a8d62f57a3d0cd1581df2fb74"
      binary "percy_darwin_arm64", target: "percy"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_linux_amd64"
      sha256 "40e929a30c8c8f7ed3bf1295746f59bd5d4522c44ff6884859e3f71911d249e2"
      binary "percy_linux_amd64", target: "percy"
    end
    on_arm do
      url "https://github.com/tgruben-circuit/percy/releases/download/v#{version}/percy_linux_arm64"
      sha256 "e0140e1782e1118ffb1c8ab6d93112988067db35c1b399958d92e5c87b6dbeaf"
      binary "percy_linux_arm64", target: "percy"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required
end
